name: Olive Examples CI | Setup Composite Workflow
description: "Composite action to setup environment"

inputs:
  shell:
    description: "Shell to use."
    required: true
    type: choice
    options: [ "bash", "cmd" ]

  python_version:
    description: "Python version to use."
    required: true

  olive_version:
    description: "Olive version to use."
    required: true

  onnxruntime:
    description: "OnnxRuntime package name."
    required: true

  onnxruntime_nightly:
    description: "Use OnnxRuntime nightly package?"
    default: false
    required: false

  requirements_file:
    description: "Name/Path of the requirement's file."
    required: true

  hf_cache_key:
    description: "Huggingface cache key to use."
    required: true

runs:
  using: "composite"
  steps:
  - name: Setup python
    uses: actions/setup-python@v5
    with:
      python-version: ${{ inputs.python_version }}
      cache: 'pip'
      cache-dependency-path: ${{ inputs.requirements_file }}

  - name: Checkout Olive (main)
    if: ${{ inputs.olive_version == 'main' }}
    uses: actions/checkout@v4
    with:
      repository: microsoft/Olive
      path: Olive

  - name: Install Olive (main)
    if: ${{ inputs.olive_version == 'main' }}
    shell: ${{ inputs.shell }}
    run: |
      echo $pwd
      ls -la .
      ls -la $GITHUB_WORKSPACE
      cd Olive
      python -m pip install .

  - name: Install Olive (main)
    if: ${{ inputs.olive_version != 'main' }}
    shell: ${{ inputs.shell }}
    run: python -m pip install "olive-ai==${{ inputs.olive_version }}"

  - name: Install OnnxRuntime-Nightly
    if: ${{ inputs.onnxruntime != '' && inputs.onnxruntime_nightly }}
    shell: ${{ inputs.shell }}
    run: |
      python -m pip install -r  https://raw.githubusercontent.com/microsoft/onnxruntime/refs/heads/main/requirements.txt
      python -m pip install ${{ inputs.onnxruntime }} --pre --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/ --disable-pip-version-check

  - name: Install OnnxRuntime
    if: ${{ inputs.onnxruntime != '' && !inputs.onnxruntime_nightly }}
    shell: ${{ inputs.shell }}
    run: python -m pip install ${{ inputs.onnxruntime }}

  - name: Install requirements
    if: ${{ inputs.requirements_file != '' }}
    shell: ${{ inputs.shell }}
    run: python -m pip install -r ${{ inputs.requirements_file }}

  - name: Setup HF Cache
    if: ${{ inputs.hf_cache_key != '' }}
    uses: actions/cache@v4
    with:
        path: ${{ env.HF_HOME }}
        key: ${{ inputs.hf_cache_key }}
